library/urls.py
from django import urls
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from . import settings
from property import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('property/', include('property.urls')),
    path('', views.home , name = "home"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register_request, name="register")
    

]

 
 
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 127.0.0.1:8000/books/list

property/urls.py
from django.urls import include, path
from . import views
 
app_name = 'property'
urlpatterns = [
   path('searchproperty/', views.searchproperty, name = "searchproperty" ),
   path('homepage/', views.home , name = "home"),
   path('result/', views.result , name = "result")
   
  
   

#    path('add/', views.add),
#    path('delete/', views.delete)
]



property/models.py
# from enum import Enum
# from queue import Empty
# from django.db import models
# from django.contrib.auth.models import User

# # Create your models here.
# # class BookType(Enum):
# #    ten_days = 1
# #    five_days = 2
# #    two_days = 3
 
# class Property(models.Model):
#    _id = models.AutoField(primary_key=True, editable=False)
#    room = models.SmallIntegerField(null=False)
#    floor = models.SmallIntegerField(null=False)
#    property_type = models.CharField(max_length=100, null=False)
#    square_meter = models.SmallIntegerField(null=False)
#    location = models.CharField(max_length=100, null=False)
#    street=models.CharField(max_length=100, null=False)
#    street_number=models.SmallIntegerField(max_length=100, null=False)
#    price= models.BigIntegerField(null=False)


#    def __str__(self):
#        return self.room +","+ self.floor+","+ self.property_type+","+ self.square_meter+","+ self.location+","+ self.street+","+ self.street_number

# class Project(models.Model):
#    type_project= models.CharField(max_length=100, null=False)
#    size_project= models.SmallIntegerField(null=False)
#    company= models.CharField(max_length=100, null=False)
#    dates= models.DateTimeField(null=True, blank=True)
#    value= models.SmallIntegerField(null=False)
#    location= models.CharField(max_length=100, null=False)
#    street = models.CharField(max_length=100, null=False)
#    street_number = models.CharField(max_length=100, null=False)
   
#    def __str__(self):
#        return self.type_project +","+self.size_project +","+self.company +","+self.dates +","+self.value +","+self.loaction +","+self.street +","+self.street_number +","



from enum import Enum
from queue import Empty
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _

# Create your models here.
# class BookType(Enum):
#    ten_days = 1
#    five_days = 2
#    two_days = 3
 
class Property(models.Model):
   _id = models.AutoField(primary_key=True, editable=False)
   room = models.SmallIntegerField(_("room"),null=False)
   floor = models.SmallIntegerField(_("floor"),null=False)
   property_type = models.CharField(_("property_type"),max_length=100, null=False)
   square_meter = models.SmallIntegerField(_("square_meter"),null=False)
   location = models.CharField(_("location"),max_length=100, null=False)
   street=models.CharField(_("street"),max_length=100, null=False)
   street_number=models.SmallIntegerField(_("street_number"),null=False)
   price= models.BigIntegerField(_("price"),null=False)


   def __str__(self):
       return self.room +","+ self.floor+","+ self.property_type+","+ self.square_meter+","+ self.location+","+ self.street+","+ self.street_number+","+ self.price
   def __repr__(self):
        return self.__str__() 

class Project(models.Model):
   type_project= models.CharField(_("type_project"),max_length=100, null=False)
   size_project= models.SmallIntegerField(_("size_project"),null=False)
   company= models.CharField(_("company"),max_length=100, null=False)
   dates= models.BigIntegerField(_("dates"),null=True, blank=True)
   location= models.CharField(_("location"),max_length=100, null=False)
   street = models.CharField(_("street"),max_length=100, null=False)
   street_number = models.CharField(_("street_number"),max_length=100, null=False)
   value= models.FloatField(_("value"),null=False)
   
   def __str__(self):
       return self.type_project +","+self.size_project +","+self.company +","+self.dates +","+self.value +","+self.loaction +","+self.street +","+self.street_number
   def __repr__(self):
        return self.__str__() 



property/forms.py
from unicodedata import name
from django import forms

class SearchingForm(forms.Form):
   room = forms.IntegerField(label='room')
   floor = forms.IntegerField(label='floor')
   property_type = forms.CharField(label='property_type ')
   square_meter = forms.IntegerField(label='square_meter')
   location = forms.CharField(label='location')
   street=forms.CharField(label='street')
   price= forms.IntegerField(label='price')
   investment_range = forms.IntegerField(label='investment_range')
   fields = '__all__'


   def __str__(self):
      return self.room +","+ self.floor+","+ self.property_type+","+ self.square_meter+","+ self.location+","+ self.street+","+ self.price+","+self.investment_range
   def __repr__(self):
         return self.__str__() 

   def get_form(self):
      return self.data.get('room'), self.data.get('floor'),self.data.get('property_type'),self.data.get('square_meter'),self.data.get('location'),self.data.get('street'),self.data.get('price'),self.data.get('investment_range')
      

property/views.py
from lib2to3.pgen2.token import GREATEREQUAL
from math import floor
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.template import RequestContext, loader
from django.contrib.auth.decorators import login_required
from library.settings import LOGIN_REDIRECT_URL
from django.contrib import messages
from property.models import Project, Property
from property.register import NewUserForm
from .forms import SearchingForm
from django.contrib.auth import login
# def list(request):
#    return HttpResponse("Hello DJANGO library")

def get_name(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SearchingForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/thanks/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = SearchingForm()

    return render(request, 'result.html', {'form': form})

 
def result(request):
    my_search = request.POST.get('searchproperty')
    new_form = SearchingForm(request.POST, request.FILES)
    new_form= new_form.get_form()
    found_apt = Property.objects.filter(room__lte = new_form[0],floor__lte = new_form[1],property_type__contains = new_form[2],square_meter__lte = new_form[3],location__contains = new_form[4],street__contains = new_form[5],price__lte = new_form[6],investment_range__lte = new_form[7]).values()
    final_price = []

    for apt in found_apt:
        apt_price=apt['price']
        # found_project = Project.objects.filter(location__contains = apt['location'],street__contains = apt['street'],street_number__range = apt['street_number']-15,).values()
        found_project = Project.objects.filter(street__contains= apt['street']).values()
        investment_range=new_form[7]
        for proj in found_project:
            our_date = proj['dates']-2022
            if new_form[7]>= our_date:

                new_price = apt_price*proj['value']
                apt_price = apt_price+new_price
            
                final_price.append(apt_price)
                
            
            

    context = {
        
        'final_price' : final_price,
        'apt':found_apt,

        'apt_price' : apt_price,
        
        'found_project' : found_project,
        'found_apt' : apt['location'],
        'room' : new_form[0],
        'floor' : new_form[1],
        'property_type' : new_form[2],
        'square_meter' : new_form[3],
        'location' : new_form[4],
        'street' : new_form[5],
        'price' : new_form[6]

    }

    return render(request,'result.html',context = context)


@login_required
def home(request):
    
#    template = loader.get_template('index.html')
   context = {
       'book_list': ['Harry Potter','Lord of the Rings','Hobbit'],
       'books':"books",
   }
  
   return render(request,'index.html',context)





def searchproperty(request):
   my_search = request.GET.get('searchproperty') 
   my_property = Property.objects.all()
   searchingform = SearchingForm(request.POST, request.FILES)
   context = ({
            'searchingform' : searchingform
            
           
        })
   return render(request,'searchproperty.html', context = context)  






def get_form(request):

    if request.method == 'POST':
        form = SearchingForm(request.POST)
        if form.is_valid():
            context = {
            'room' : form.cleaned_data['room'],
            'floor' : form.cleaned_data['floor'],
            'property_type' : form.cleaned_data['property_type'],
            'square_meter' : form.cleaned_data['square_meter'],
            'location' : form.cleaned_data['location'],
            'street' : form.cleaned_data['street'],
            'street_number' : form.cleaned_data['street_number'],
            'price' : form.cleaned_data['price']
            }
            
          

            return HttpResponseRedirect('/result',  context_instance=RequestContext(request))
    else:
        form = SearchingForm()
        rendered_form = form.render("searchproperty.html")
        context = {'form': rendered_form}
        
        return render(request, 'property/result.html', context)



def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("login.html")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="register.html", context={"register_form":form})


property/templates/register.html
{% extends "base.html" %}

{% block content %} 

   

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form}}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/accounts/login">login</a> instead.</p>
</div>

{% endblock %}

property/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
 


{{ found_project }}

{{ apt_price }}

{{ apt }}
   


</body>
</html>

property/templates/searchproperty.html
{% extends 'base.html' %}


<!DOCTYPE html>
<html lang="en">
<head>
        
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
</head>
<body>
        
        {% block content %}
        
        <form action="{% url 'property:result' %}" method="POST" enctype=multipart/form-data name="searchproperty">
          {% csrf_token %}
        
            <!-- {{ searchingform.as_table }}   -->
            {{ searchingform.non_field_errors }}
            <div class="fieldWrapper">
                {{ searchingform.room.errors }}
                <label for="{{ form.room.id_for_label }}">room:</label>
                {{ searchingform.room }}
                
            </div>

            {{ searchingform.non_field_errors }}
            <div class="fieldWrapper">
                {{ searchingform.floor.errors }}
                <label for="{{ form.floor.id_for_label }}">floor:</label>
                {{ searchingform.floor }}
                
            </div>

            {{ searchingform.non_field_errors }}
            <div class="fieldWrapper">
                {{ searchingform.property_type.errors }}
                <label for="{{ form.property_type.id_for_label }}">property type:</label>
                {{ searchingform.property_type }}
                
            </div>
            {{ searchingform.non_field_errors }}
            <div class="fieldWrapper">
                {{ searchingform.square_meter.errors }}
                <label for="{{ form.square_meter.id_for_label }}">square meter:</label>
                {{ searchingform.square_meter }}
                
            </div>
            {{ searchingform.non_field_errors }}
            <div class="fieldWrapper">
                {{ searchingform.location.errors }}
                <label for="{{ form.location.id_for_label }}">location:</label>
                {{ searchingform.location }}
                
            </div>
            {{ searchingform.non_field_errors }}
            <div class="fieldWrapper">
                {{ searchingform.street.errors }}
                <label for="{{ form.street.id_for_label }}">street:</label>
                {{ searchingform.street }}
                
            </div>
         
            {{ searchingform.non_field_errors }}
            <div class="fieldWrapper">
                {{ searchingform.price.errors }}
                <label for="{{ form.price.id_for_label }}">price</label>
                {{ searchingform.price }}
                
            </div>
            {{ searchingform.non_field_errors }}
            <div class="fieldWrapper">
                {{ searchingform.investment_range.errors }}
                <label for="{{ form.investment_range.id_for_label }}">investment_range</label>
                {{ searchingform.investment_range }}
                
            </div>









          

                <!-- <div class="form-group row">
                  <label for="colFormLabel" class="col-sm-2 col-form-label">Room size</label>
                  <div class="col-sm-10">
                    <input type="number" name="roomnumber" class="form-control" id="colFormLabel" placeholder="Enter number of rooms 0-5">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="colFormLabel" class="col-sm-2 col-form-label">Desiered floor</label>
                  <div class="col-sm-10">
                    <input type="number" name="floor" class="form-control" id="colFormLabel" placeholder="Enter the floor you want(MAX)">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="colFormLabel" class="col-sm-2 col-form-label">Property Type</label>
                  <div class="col-sm-10">
                    <input type="text" name="house type" class="form-control" id="colFormLabel" placeholder="house/apartment">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="colFormLabel" class="col-sm-2 col-form-label">Square meter</label>
                  <div class="col-sm-10">
                    <input type="number" name="square meter" class="form-control" id="colFormLabel" placeholder="Enter how mush square meter do you want?(MAX)">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="colFormLabel" class="col-sm-2 col-form-label">City</label>
                  <div class="col-sm-10">
                    <input type="text" name="city" class="form-control" id="colFormLabel" placeholder="Which city do you want?">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="colFormLabel" class="col-sm-2 col-form-label">Street</label>
                  <div class="col-sm-10">
                    <input type="text" name="street" class="form-control" id="colFormLabel" placeholder="Which street do you want?">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="colFormLabel" class="col-sm-2 col-form-label">Price</label>
                  <div class="col-sm-10">
                    <input type="number" name="price" class="form-control" id="colFormLabel" placeholder="Enter your maximum price">
                  </div>
                </div>
                <div class="form-group row">
                  <label for="colFormLabel" class="col-sm-2 col-form-label">Investment range</label>
                  <div class="col-sm-10">
                    <input type="number" name="years" class="form-control" id="colFormLabel" placeholder="For how many years you'r looking to invest?(MAX)">
                  </div>
                </div> -->
                
                  <input type="submit" value = 'submit'>
          
              </form> -->
        {% endblock %}     
        
</body>
</html>
